const { ethers } = require("hardhat");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);

  // On Arc testnet, USDC is already deployed. Set in .env or use a mock for local.
  const usdcAddress = process.env.USDC_ADDRESS || (await deployMockUsdc(deployer));

  // 1. ProviderRegistry
  const Registry = await ethers.getContractFactory("ProviderRegistry");
  const registry = await Registry.deploy(usdcAddress);
  await registry.waitForDeployment();
  console.log("ProviderRegistry:", await registry.getAddress());

  // 2. CommitReveal
  const CommitReveal = await ethers.getContractFactory("CommitReveal");
  const commitReveal = await CommitReveal.deploy();
  await commitReveal.waitForDeployment();
  console.log("CommitReveal:", await commitReveal.getAddress());

  // 3. ZK Verifier (generated by snarkjs; deploy separately, address passed here)
  const zkVerifierAddress = process.env.ZK_VERIFIER_ADDRESS || ethers.ZeroAddress;

  // 4. SignalMarket
  const Market = await ethers.getContractFactory("SignalMarket");
  const market = await Market.deploy(
    usdcAddress,
    await registry.getAddress(),
    await commitReveal.getAddress(),
    zkVerifierAddress
  );
  await market.waitForDeployment();
  console.log("SignalMarket:", await market.getAddress());

  console.log("\nAdd to .env:");
  console.log(`PROVIDER_REGISTRY_ADDRESS=${await registry.getAddress()}`);
  console.log(`COMMIT_REVEAL_ADDRESS=${await commitReveal.getAddress()}`);
  console.log(`SIGNAL_MARKET_ADDRESS=${await market.getAddress()}`);
}

async function deployMockUsdc(deployer) {
  const MockERC20 = await ethers.getContractFactory("MockERC20");
  const mock = await MockERC20.deploy("USD Coin", "USDC", 6);
  await mock.waitForDeployment();
  const addr = await mock.getAddress();
  console.log("MockUSDC:", addr);
  // Mint 10M USDC to deployer for testing
  await mock.mint(deployer.address, ethers.parseUnits("10000000", 6));
  return addr;
}

main().catch((e) => { console.error(e); process.exit(1); });
